---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: PUT YOUR TASK NAME HERE - THIS SECTION ALSO DESCRIBE USE OF DEFAULT VARIABLES
  get_url:
    url: "{{ var1 }}"
    dest: "{{ var2 }}"
    mode: 0600
    backup: yes
  when: ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"
  
- name: USE OF TEMPLATES, VARS & HANDLERS 
  template:
    src: template.txt
    dest: /tmp/{{ var4 }}
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart Apache
  when: ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"
   
